image: maven:3-jdk-8

before_script:
  - git submodule update --init --recursive
  - cd wisecraft-i18n
  - git pull origin master
  - cd ../statusesLayout
  - git pull origin master
  - cd ../MaterialIcons
  - git config --global user.email "nao20010128@gmail.com"
  - git config --global user.name "nao20010128nao"
  - git pull origin master
  - cd ../
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes --force-yes wget tar unzip openjdk-7-jdk lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-23.0.2,build-tools-21.1.0,build-tools-23.0.3,android-21,android-23,extra-android-m2repository
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - java -version

stages:
  - main
  - rcon
  - rconPC
  - mainEx
  - mainOld

main:
  stage: main
  script:
    - cd MaterialIcons
    - git remote set-url origin https://github.com/nao20010128nao/MaterialIconsLight.git
    - git pull origin master > NUL
    - cd ../
    - gradle-2.12/bin/gradle assembleRelease -p app --info --stacktrace
    - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/Wisecraft-release.apk
    - mv app/build/outputs/apk/*.apk .
    - unzip Wisecraft-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


rcon:
  stage: rcon
  script:
    - gradle-2.12/bin/gradle assembleRelease -p rconApp --info --stacktrace
    - mv rconApp/build/outputs/apk/rconApp-release.apk rconApp/build/outputs/apk/WRcon-release.apk
    - mv rconApp/build/outputs/apk/*.apk .
    - rm app*.apk
    - rm Wisecraft*.apk
    - rm dexdump.txt
    - unzip WRcon-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


rconPC:
  stage: rconPC
  script:
    - gradle-2.12/bin/gradle assembleRelease -p rconPassCrack --info --stacktrace
    - mv rconPassCrack/build/outputs/apk/*.apk .
    - rm dexdump.txt
    - unzip rconPassCrack-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "rconPassCrack*.apk"
      - dexdump.txt

mainEx:
  stage: mainEx
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - cd MaterialIcons
    - git remote set-url origin https://github.com/nao20010128nao/MaterialIconsEx.git
    - git pull origin master > NUL
    - cd ../
    - gradle-2.12/bin/gradle assembleRelease -p app --info --stacktrace
    - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/Wisecraft-release.apk
    - mv app/build/outputs/apk/*.apk .
    - unzip Wisecraft-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


mainOld:
  stage: mainOld
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - gradle-2.12/bin/gradle assembleRelease -p app --info --stacktrace
    - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/Wisecraft-release.apk
    - mv app/build/outputs/apk/*.apk .
    - unzip Wisecraft-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


