image: maven:3-jdk-8

before_script:
  - chmod a+x ./ci/*
  - source ./ci/prepare.sh 2> /dev/null

stages:
#  - elim
  - main
  - copy

main:
  stage: main
  script:
    - gradle-2.14.1/bin/gradle build --info --stacktrace > build.log
    - mv */build/outputs/apk/*.apk .
    - unzip app-release.apk -d unzippedApkA > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkA/classes.dex > dexdump-app.txt
    - unzip rconApp-release.apk -d unzippedApkB > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkB/classes.dex > dexdump-rcon.txt
    - unzip rconPassCrack-release.apk -d unzippedApkC > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkC/classes.dex > dexdump-rconPC.txt
    - grep "Git\sRevision" build.log
    - tree > tree.log
  artifacts:
    paths:
      - "*.apk"
      - dexdump*.txt
      - build.log
      - powof2.txt
      - "*/build/outputs/aar/*"
      - tree.log
      - "*/build/outputs/mapping/*/mapping.txt"


#elim:
#  stage: elim
#  script:
#    - gradle-2.14.1/bin/gradle eliminateImplementTodo --info --stacktrace
    
copy:
  stage: copy
  script:
    - "git clone https://github.com/RevealEverything/Files.git"
    - cd Files
    - "git remote add dest https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/nao20010128nao/Wisecraft_Steals_2.git"
    - git fetch dest
    - git push dest master
    - cd ..
    - "git clone https://$GITLAB_USER:$GITLAB_PASS@gitlab.com/nao20010128nao/Wisecraft.git"
    - cd Wisecraft
    - "git remote add dest https://$GITHUB_USER:$GITHUB_PASS@github.com/nao20010128nao/Wisecraft-mirror"
    - git fetch dest
    - git push dest master
