image: maven:3-jdk-8

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet upgrade --yes
  - apt-get --quiet install --yes --force-yes wget tar unzip lib32stdc++6 lib32z1
  - git config --global user.email "nao20010128@gmail.com"
  - git config --global user.name "nao20010128nao"
  - git submodule update --init --recursive
  - cd wisecraft-i18n
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../statusesLayout
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../MaterialIcons
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../calligraphy
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../psts
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../colorPicker
  - git pull origin master > NUL
  - git checkout master > NUL
  - cd ../
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-23.0.2,build-tools-21.1.0,build-tools-23.0.3,build-tools-24.0.0,android-21,android-23,android-24,extra-android-m2repository,extra-google-m2repository
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - java -version

stages:
  - main
  - rcon
  - rconPC

main:
  stage: main
  script:
    - gradle-2.12/bin/gradle build -p app --info --stacktrace
    - mv app/build/outputs/apk/*.apk .
    - unzip app-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


rcon:
  stage: rcon
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - gradle-2.12/bin/gradle build -p rconApp --info --stacktrace
    - mv rconApp/build/outputs/apk/*.apk .
    - unzip rconApp-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt


rconPC:
  stage: rconPC
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - gradle-2.12/bin/gradle build -p rconPassCrack --info --stacktrace
    - mv rconPassCrack/build/outputs/apk/*.apk .
    - unzip rconPassCrack-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/23.0.2/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "rconPassCrack*.apk"
      - dexdump.txt


