image: maven:3-jdk-8

before_script:
  - apt-get --quiet update --yes > NUL
  - apt-get --quiet upgrade --yes > NUL
  - apt-get --quiet install --yes --force-yes wget tar unzip lib32stdc++6 lib32z1 > NUL
  - chmod a+x ./ci/git.sh
  - ./ci/git.sh 2> NUL
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-24.0.0,android-24,extra-android-m2repository,extra-google-m2repository > NUL
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - java -version

stages:
  - main
  - rcon
  - rconPC

main:
  stage: main
  script:
    - gradle-2.14.1/bin/gradle build -p app --info --stacktrace > build.log
    - mv app/build/outputs/apk/*.apk .
    - unzip app-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApk/classes.dex > dexdump.txt
    - grep "Git\sRevision" build.log
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt
      - build.log


rcon:
  stage: rcon
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - gradle-2.14.1/bin/gradle build -p rconApp --info --stacktrace > build.log
    - mv rconApp/build/outputs/apk/*.apk .
    - unzip rconApp-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt
      - build.log


rconPC:
  stage: rconPC
  script:
    - "rm *.apk"
    - rm dexdump.txt
    - gradle-2.14.1/bin/gradle build -p rconPassCrack --info --stacktrace > build.log
    - mv rconPassCrack/build/outputs/apk/*.apk .
    - unzip rconPassCrack-release.apk -d unzippedApk > NUL
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApk/classes.dex > dexdump.txt
  artifacts:
    paths:
      - "*.apk"
      - dexdump.txt
      - build.log


