image: maven:3-jdk-8

before_script:
  - apt-get --quiet update --yes > /dev/null
  - apt-get --quiet upgrade --yes > /dev/null
  - apt-get --quiet install --yes --force-yes wget tar unzip lib32stdc++6 lib32z1 gzip > /dev/null
  - chmod a+x ./ci/git.sh
  - ./ci/git.sh 2> /dev/null
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-24.0.0,android-24,extra-android-m2repository,extra-google-m2repository > /dev/null
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export POW_OF_2=false
  - java -version

stages:
#  - elim
  - main

main:
  stage: main
  script:
    - gradle-2.14.1/bin/gradle build --info --stacktrace > build.log
    - mv */build/outputs/apk/*.apk .
    - unzip app-release.apk -d unzippedApkA > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkA/classes.dex > dexdump-app.txt
    - unzip rconApp-release.apk -d unzippedApkB > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkB/classes.dex > dexdump-rcon.txt
    - unzip rconPassCrack-release.apk -d unzippedApkC > /dev/null
    - android-sdk-linux/build-tools/24.0.0/dexdump -d unzippedApkC/classes.dex > dexdump-rconPC.txt
    - grep "Git\sRevision" build.log
  artifacts:
    paths:
      - "*.apk"
      - dexdump*.txt
      - build.log
      - powof2.txt


#elim:
#  stage: elim
#  script:
#    - gradle-2.14.1/bin/gradle eliminateImplementTodo --info --stacktrace
    
