image: nao20010128nao/android-build

before_script:
  - chmod a+x ./ci/*
  - source ./ci/prepare.sh 2> /dev/null

stages:
  - main
  - copy

main:
  stage: main
  script:
    - gradle build --info --stacktrace > build.log
    - mv */build/outputs/apk/*.apk .
    - unzip app-release.apk -d unzippedApkA > /dev/null
    - $ANDROID_HOME/build-tools/25.0.0/dexdump -d unzippedApkA/classes.dex > dexdump-app.txt
    - unzip rconApp-release.apk -d unzippedApkB > /dev/null
    - $ANDROID_HOME/build-tools/25.0.0/dexdump -d unzippedApkB/classes.dex > dexdump-rcon.txt
    - unzip rconPassCrack-release.apk -d unzippedApkC > /dev/null
    - $ANDROID_HOME/build-tools/25.0.0/dexdump -d unzippedApkC/classes.dex > dexdump-rconPC.txt
    - grep "Git\sRevision" build.log
    - tree > tree.log
  artifacts:
    paths:
      - "*.apk"
      - dexdump*.txt
      - build.log
      - powof2.txt
      - "*/build/outputs/aar/*"
      - tree.log
      - "*/build/outputs/mapping/*/mapping.txt"

copy:
  stage: copy
  script:
    - source ./ci/copy.sh