/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.support.v7.cardview;

public final class R {
    public static final class attr {
        /**  Background color for CardView. 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardBackgroundColor=com.nao20010128nao.Wisecraft.R.attr.cardBackgroundColor;
        /**  Corner radius for CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardCornerRadius=com.nao20010128nao.Wisecraft.R.attr.cardCornerRadius;
        /**  Elevation for CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardElevation=com.nao20010128nao.Wisecraft.R.attr.cardMaxElevation;
        /**  Maximum Elevation for CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardMaxElevation=com.nao20010128nao.Wisecraft.R.attr.cardMaxElevation;
        /**  Add padding to CardView on v20 and before to prevent intersections between the Card content and rounded corners. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardPreventCornerOverlap=com.nao20010128nao.Wisecraft.R.attr.cardPreventCornerOverlap;
        /**  Add padding in API v21+ as well to have the same measurements with previous versions. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int cardUseCompatPadding=com.nao20010128nao.Wisecraft.R.attr.cardUseCompatPadding;
        /**  Inner padding between the edges of the Card and children of the CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentPadding=com.nao20010128nao.Wisecraft.R.attr.contentPadding;
        /**  Inner padding between the bottom edge of the Card and children of the CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentPaddingBottom=com.nao20010128nao.Wisecraft.R.attr.contentPaddingBottom;
        /**  Inner padding between the left edge of the Card and children of the CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentPaddingLeft=com.nao20010128nao.Wisecraft.R.attr.contentPaddingLeft;
        /**  Inner padding between the right edge of the Card and children of the CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentPaddingRight=com.nao20010128nao.Wisecraft.R.attr.contentPaddingRight;
        /**  Inner padding between the top edge of the Card and children of the CardView. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int contentPaddingTop=com.nao20010128nao.Wisecraft.R.attr.contentPaddingTop;
    }
    public static final class color {
        public static int cardview_dark_background=com.nao20010128nao.Wisecraft.R.color.cardview_dark_background;
        public static int cardview_light_background=com.nao20010128nao.Wisecraft.R.color.cardview_light_background;
        public static int cardview_shadow_end_color=com.nao20010128nao.Wisecraft.R.color.cardview_shadow_end_color;
        public static int cardview_shadow_start_color=com.nao20010128nao.Wisecraft.R.color.cardview_shadow_start_color;
    }
    public static final class dimen {
        public static int cardview_compat_inset_shadow=com.nao20010128nao.Wisecraft.R.dimen.cardview_compat_inset_shadow;
        public static int cardview_default_elevation=com.nao20010128nao.Wisecraft.R.dimen.cardview_default_elevation;
        public static int cardview_default_radius=com.nao20010128nao.Wisecraft.R.dimen.cardview_default_radius;
    }
    public static final class style {
        public static int CardView=com.nao20010128nao.Wisecraft.R.style.CardView;
        public static int CardView_Dark=com.nao20010128nao.Wisecraft.R.style.CardView_Dark;
        public static int CardView_Light=com.nao20010128nao.Wisecraft.R.style.CardView_Light;
    }
    public static final class styleable {
        /** Attributes that can be used with a CardView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CardView_cardBackgroundColor android.support.v7.cardview:cardBackgroundColor}</code></td><td> Background color for CardView.</td></tr>
           <tr><td><code>{@link #CardView_cardCornerRadius android.support.v7.cardview:cardCornerRadius}</code></td><td> Corner radius for CardView.</td></tr>
           <tr><td><code>{@link #CardView_cardElevation android.support.v7.cardview:cardElevation}</code></td><td> Elevation for CardView.</td></tr>
           <tr><td><code>{@link #CardView_cardMaxElevation android.support.v7.cardview:cardMaxElevation}</code></td><td> Maximum Elevation for CardView.</td></tr>
           <tr><td><code>{@link #CardView_cardPreventCornerOverlap android.support.v7.cardview:cardPreventCornerOverlap}</code></td><td> Add padding to CardView on v20 and before to prevent intersections between the Card content and rounded corners.</td></tr>
           <tr><td><code>{@link #CardView_cardUseCompatPadding android.support.v7.cardview:cardUseCompatPadding}</code></td><td> Add padding in API v21+ as well to have the same measurements with previous versions.</td></tr>
           <tr><td><code>{@link #CardView_contentPadding android.support.v7.cardview:contentPadding}</code></td><td> Inner padding between the edges of the Card and children of the CardView.</td></tr>
           <tr><td><code>{@link #CardView_contentPaddingBottom android.support.v7.cardview:contentPaddingBottom}</code></td><td> Inner padding between the bottom edge of the Card and children of the CardView.</td></tr>
           <tr><td><code>{@link #CardView_contentPaddingLeft android.support.v7.cardview:contentPaddingLeft}</code></td><td> Inner padding between the left edge of the Card and children of the CardView.</td></tr>
           <tr><td><code>{@link #CardView_contentPaddingRight android.support.v7.cardview:contentPaddingRight}</code></td><td> Inner padding between the right edge of the Card and children of the CardView.</td></tr>
           <tr><td><code>{@link #CardView_contentPaddingTop android.support.v7.cardview:contentPaddingTop}</code></td><td> Inner padding between the top edge of the Card and children of the CardView.</td></tr>
           </table>
           @see #CardView_cardBackgroundColor
           @see #CardView_cardCornerRadius
           @see #CardView_cardElevation
           @see #CardView_cardMaxElevation
           @see #CardView_cardPreventCornerOverlap
           @see #CardView_cardUseCompatPadding
           @see #CardView_contentPadding
           @see #CardView_contentPaddingBottom
           @see #CardView_contentPaddingLeft
           @see #CardView_contentPaddingRight
           @see #CardView_contentPaddingTop
         */
        public static final int[] CardView = com.nao20010128nao.Wisecraft.R.styleable.CardView;
        /**
          <p>
          @attr description
           Background color for CardView. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardBackgroundColor
        */
        public static int CardView_cardBackgroundColor = com.nao20010128nao.Wisecraft.R.styleable.CardView_cardBackgroundColor;
        /**
          <p>
          @attr description
           Corner radius for CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardCornerRadius
        */
        public static int CardView_cardCornerRadius = com.nao20010128nao.Wisecraft.R.styleable.CardView_cardCornerRadius;
        /**
          <p>
          @attr description
           Elevation for CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardElevation
        */
        public static int CardView_cardElevation = 2;
        /**
          <p>
          @attr description
           Maximum Elevation for CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardMaxElevation
        */
        public static int CardView_cardMaxElevation = com.nao20010128nao.Wisecraft.R.styleable.CardView_cardMaxElevation;
        /**
          <p>
          @attr description
           Add padding to CardView on v20 and before to prevent intersections between the Card content and rounded corners. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardPreventCornerOverlap
        */
        public static int CardView_cardPreventCornerOverlap = com.nao20010128nao.Wisecraft.R.styleable.CardView_cardPreventCornerOverlap;
        /**
          <p>
          @attr description
           Add padding in API v21+ as well to have the same measurements with previous versions. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:cardUseCompatPadding
        */
        public static int CardView_cardUseCompatPadding = com.nao20010128nao.Wisecraft.R.styleable.CardView_cardUseCompatPadding;
        /**
          <p>
          @attr description
           Inner padding between the edges of the Card and children of the CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:contentPadding
        */
        public static int CardView_contentPadding = com.nao20010128nao.Wisecraft.R.styleable.CardView_contentPadding;
        /**
          <p>
          @attr description
           Inner padding between the bottom edge of the Card and children of the CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:contentPaddingBottom
        */
        public static int CardView_contentPaddingBottom = com.nao20010128nao.Wisecraft.R.styleable.CardView_contentPaddingBottom;
        /**
          <p>
          @attr description
           Inner padding between the left edge of the Card and children of the CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:contentPaddingLeft
        */
        public static int CardView_contentPaddingLeft = com.nao20010128nao.Wisecraft.R.styleable.CardView_contentPaddingLeft;
        /**
          <p>
          @attr description
           Inner padding between the right edge of the Card and children of the CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:contentPaddingRight
        */
        public static int CardView_contentPaddingRight = com.nao20010128nao.Wisecraft.R.styleable.CardView_contentPaddingRight;
        /**
          <p>
          @attr description
           Inner padding between the top edge of the Card and children of the CardView. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android.support.v7.cardview:contentPaddingTop
        */
        public static int CardView_contentPaddingTop = com.nao20010128nao.Wisecraft.R.styleable.CardView_contentPaddingTop;
    };
}
